# Generated by Django 5.1.6 on 2025-03-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0003_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
