# Generated by Django 5.1.6 on 2025-03-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0006_appointment_doctor_alter_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='dosage',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medication',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
