# Generated by Django 5.1.6 on 2025-03-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0007_medicalrecord_dosage_medicalrecord_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='license_number',
        ),
    ]
