# Generated by Django 5.1.6 on 2025-03-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Link', '0008_remove_profile_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='total_revenue',
        ),
    ]
